YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "Bizs",
        "JC",
        "JC.AjaxUpload",
        "JC.AutoChecked",
        "JC.AutoComplete",
        "JC.AutoSelect",
        "JC.BaseMVC",
        "JC.BaseMVC.Model",
        "JC.Calendar",
        "JC.Dialog",
        "JC.Dialog.alert",
        "JC.Dialog.confirm",
        "JC.Dialog.mask",
        "JC.Dialog.msgbox",
        "JC.Fixed",
        "JC.Form",
        "JC.LunarCalendar",
        "JC.Panel",
        "JC.Placeholder",
        "JC.Slider",
        "JC.Suggest",
        "JC.Tab",
        "JC.Tips",
        "JC.Tree",
        "JC.Valid",
        "JC.alert",
        "JC.common",
        "JC.confirm",
        "JC.hideAllPanel",
        "JC.hideAllPopup",
        "JC.msgbox",
        "jQuery",
        "window.Bizs.ActionLogic",
        "window.Bizs.AutoSelectComplete",
        "window.Bizs.ChangeLogic",
        "window.Bizs.CommonModify",
        "window.Bizs.FormLogic",
        "window.Bizs.KillISPCache",
        "window.Bizs.MoneyTips",
        "window.Bizs.MultiDate"
    ],
    "modules": [],
    "allModules": []
} };
});